import type { Metadata } from "next";
import "./globals.css";
import Login from "./login/page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div>
            <div className=" h-full flex flex-col">{children}</div>
            {/* <div><Login></Login></div> */}
        </div>

      </body>
    </html>
  );
}
